export const SET_DISPLAY_RESULT = 'SET_DISPLAY_RESULT'

export const ACCUMULATOR_POP = 'ACCUMULATOR_POP'
export const ACCUMULATOR_PUSH = 'ACCUMULATOR_PUSH'
export const ACCUMULATOR_CLEAR = 'ACCUMULATOR_CLEAR'
export const ACCUMULATOR_REPLACE_LAST = 'ACCUMULATOR_REPLACE_LAST'

export const HISTORY_PUSH = 'HISTORY_PUSH'
export const HISTORY_CLEAR = 'HISTORY_CLEAR'
export const HISTORY_ERROR = 'HISTORY_ERROR'
export const HISTORY_FETCH_ERROR = 'HISTORY_FETCH_ERROR'
export const HISTORY_FETCH_PENDING = 'HISTORY_FETCH_PENDING'
export const HISTORY_FETCH_COMPLETED = 'HISTORY_FETCH_COMPLETED'
// prettier-ignore
export const HISTORY_POST_CALCULATION_PENDING = 'HISTORY_POST_CALCULATION_PENDING'
// prettier-ignore
export const HISTORY_POST_CALCULATION_REJECTED = 'HISTORY_POST_CALCULATION_REJECTED'
// prettier-ignore
export const HISTORY_POST_CALCULATION_COMPLETED = 'HISTORY_POST_CALCULATION_COMPLETED'

export const UI_HIDE_MOBILE_HISTORY_PANEL = 'UI_HIDE_MOBILE_HISTORY_PANEL'
export const UI_SHOW_MOBILE_HISTORY_PANEL = 'UI_SHOW_MOBILE_HISTORY_PANEL'
export const UI_TOGGLE_MOBILE_HISTORY_PANEL = 'UI_TOGGLE_MOBILE_HISTORY_PANEL'
