export const SET_DISPLAY_RESULT = 'SET_DISPLAY_RESULT'

export const ACCUMULATOR_PUSH = 'ACCUMULATOR_PUSH'
export const ACCUMULATOR_CLEAR = 'ACCUMULATOR_CLEAR'
export const ACCUMULATOR_REPLACE_LAST = 'ACCUMULATOR_REPLACE_LAST'

export const HISTORY_PUSH = 'HISTORY_PUSH'
export const HISTORY_CLEAR = 'HISTORY_CLEAR'
export const HISTORY_APPLY = 'HISTORY_APPLY'
export const HISTORY_ERROR = 'HISTORY_ERROR'
