export const buttons = {
  // numbers
  BTN_NUM_ZERO: 0,
  BTN_NUM_ONE: 1,
  BTN_NUM_TWO: 2,
  BTN_NUM_THREE: 3,
  BTN_NUM_FOUR: 4,
  BTN_NUM_FIVE: 5,
  BTN_NUM_SIX: 6,
  BTN_NUM_SEVEN: 7,
  BTN_NUM_EIGHT: 8,
  BTN_NUM_NINE: 9,

  // operations
  BTN_PERCENT: 10,
  BTN_CANCEL_ENTRY: 11,
  BTN_CLEAR: 12,
  BTN_REMOVE: 13,
  BTN_ONE_DIVIDE_BY: 14,
  BTN_SQUARE: 15,
  BTN_SQUARE_ROOT: 16,
  BTN_DIVIDE: 17,
  BTN_MULTIPLY: 18,
  BTN_SUBTRACT: 19,
  BTN_ADD: 20,
  BTN_SIGN: 21,
  BTN_FLOATING_POINT: 22,
  BTN_EQUAL: 23,
}
